# This is a basic workflow to help you get started with Actions

name: Update Clash Gists

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "dler" ]
  pull_request:
    branches: [ "dler" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Clone Personal Proxies Override
        run: |
          rm -rf proxies
          git clone https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ secrets.PERSONAL_PROXIES_GIT }}
      - name: Generate ClashXPro configuration
        run: sh ./sh/gen_clash_config.sh ${{ secrets.DLER_SUBSCRIBE_TOKEN }}
      # Update clash_config.yaml to gist 
      - name: Deploy
        uses: exuanbo/actions-deploy-gist@v1
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gist_id: ${{ secrets.GIST_ID }}
          gist_file_name: clash_config.yaml
          file_path: ./gen/config/clash_config.yaml
          file_type: text
